export const SET_PRODUCT_DATA = `SET_PRODUCT_DATA`;
export const ADD_PRODUCT_DATA = `ADD_PRODUCT_DATA`;
export const DELETE_PRODUCT = `DELETE_PRODUCT`;

export const ADD_CART_DATA = `ADD_CART_DATA`;
export const REMOVE_CART_DATA = `REMOVE_CART_DATA`;
export const CLEAR_CART_DATA = `CLEAR_CART_DATA`;

export const SET_ORDER_DATA = `SET_ORDER_DATA`;
export const UPDATE_STATUS = `UPDATE_STATUS`;
export const DELETE_ORDER_DATA = `DELETE_ORDER_DATA`;

export const SET_USER = `SET_USER`;
export const CLEAR_USER = `CLEAR_USER`;
