export const SET_PRODUCT_DATA = `SET_PRODUCT_DATA`;

export const ADD_CART_DATA = `ADD_CART_DATA`;
export const REMOVE_CART_DATA = `REMOVE_CART_DATA`;
export const CLEAR_CART_DATA = `CLEAR_CART_DATA`;

export const SET_ORDER_DATA = `SET_ORDER_DATA`;
