import { Inter } from "next/font/google";
// import "./globals.css";
import StoreProvider from "./store/StoreProvider";
import Navbar from "@/component/Navbar";
import Sidebar from "@/component/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          <Sidebar />
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
